# Generated by Django 4.2 on 2024-05-22 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captain',
            fields=[
                ('captain_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=32)),
                ('captain_budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('discord_name', models.CharField(max_length=32)),
                ('smite_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_1', models.CharField(default='Fill', max_length=16)),
                ('role_2', models.CharField(default='Fill', max_length=16)),
                ('estimated_value', models.IntegerField()),
                ('captain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.captain')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.user')),
            ],
        ),
        migrations.AddField(
            model_name='captain',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.user'),
        ),
    ]
