# Generated by Django 4.2 on 2024-05-25 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tournament_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='tournament_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
    ]
