# Generated by Django 4.2 on 2024-05-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_user_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.CharField(default='None', max_length=256),
        ),
        migrations.AddField(
            model_name='tournament',
            name='title',
            field=models.CharField(default='Glaeria Smite League', max_length=64),
        ),
    ]
