# Generated by Django 4.2 on 2024-05-25 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 25, 15, 56, 6, 27181, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 15, 56, 6, 27181, tzinfo=datetime.timezone.utc)),
        ),
    ]
