# Generated by Django 4.2 on 2024-05-25 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_time_alter_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='captain_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.captain'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 21, 20, 730005,
                                                             tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 25, 16, 21, 20, 730005,
                                                             tzinfo=datetime.timezone.utc)),
        ),
    ]
