# Generated by Django 4.2 on 2024-05-25 16:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_player_captain_id_alter_tournament_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tournament_id',
        ),
        migrations.AddField(
            model_name='player',
            name='tournament_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 25, 39, 74349,
                                                             tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 25, 16, 25, 39, 74349,
                                                             tzinfo=datetime.timezone.utc)),
        ),
    ]
