# Generated by Django 4.2 on 2024-05-25 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_player_tournament_id_alter_tournament_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 25, 16, 28, 12, 789634,
                                                             tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 25, 16, 28, 12, 789634,
                                                             tzinfo=datetime.timezone.utc)),
        ),
    ]
